from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


APP_DIR = Path(__file__).resolve().parents[1]
ENV_FILE = APP_DIR / ".env.supabase.local"
BUCKET = "job-assistant-users"


def run_json(command: list[str]) -> list | dict:
    result = subprocess.run(command, text=True, capture_output=True, timeout=60)
    if result.returncode != 0:
        raise SystemExit(result.stderr.strip() or result.stdout.strip())
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Could not parse JSON from: {' '.join(command)}") from exc


def choose_project(projects: list[dict]) -> dict:
    if not projects:
        raise SystemExit("No Supabase projects found. Create a free Supabase project first.")
    preferred = [p for p in projects if "job" in (p.get("name") or "").lower() or "assistant" in (p.get("name") or "").lower()]
    if len(preferred) == 1:
        return preferred[0]
    active = [p for p in projects if (p.get("status") or "").upper() in {"ACTIVE_HEALTHY", "ACTIVE"}]
    candidates = active or projects
    if len(candidates) == 1:
        return candidates[0]
    print("Supabase projects:")
    for index, project in enumerate(candidates, start=1):
        print(f"{index}. {project.get('name')} ({project.get('id') or project.get('ref')})")
    raw = input("Choose project number: ").strip()
    try:
        return candidates[int(raw) - 1]
    except Exception as exc:
        raise SystemExit("Invalid project selection.") from exc


def key_value(keys: list[dict], names: set[str]) -> str:
    for item in keys:
        name = str(item.get("name") or item.get("key") or "").lower()
        if name in names:
            return item.get("api_key") or item.get("value") or item.get("key_value") or ""
    return ""


def main() -> None:
    projects = run_json(["supabase", "projects", "list", "--output-format", "json"])
    project = choose_project(projects if isinstance(projects, list) else projects.get("projects", []))
    project_ref = project.get("id") or project.get("ref") or project.get("project_ref")
    if not project_ref:
        raise SystemExit("Could not determine Supabase project ref.")
    keys_payload = run_json(["supabase", "projects", "api-keys", "--project-ref", project_ref, "--output-format", "json"])
    keys = keys_payload if isinstance(keys_payload, list) else keys_payload.get("api_keys", [])
    anon = key_value(keys, {"anon", "anon key", "public"})
    service_role = key_value(keys, {"service_role", "service role", "service_role key"})
    if not anon or not service_role:
        raise SystemExit("Could not find anon and service_role keys from Supabase CLI output.")
    url = project.get("api_url") or project.get("rest_url") or f"https://{project_ref}.supabase.co"
    text = "\n".join([
        "# Generated by scripts/autofill_supabase_from_cli.py",
        f"SUPABASE_URL={url}",
        f"SUPABASE_ANON_KEY={anon}",
        f"SUPABASE_SERVICE_ROLE_KEY={service_role}",
        "SUPABASE_JWT_SECRET=",
        f"SUPABASE_STORAGE_BUCKET={BUCKET}",
        "",
    ])
    ENV_FILE.write_text(text, encoding="utf-8")
    print(f"Wrote {ENV_FILE}")
    subprocess.run([sys.executable, str(APP_DIR / "scripts" / "configure_render_supabase.py"), str(ENV_FILE)], check=True)


if __name__ == "__main__":
    main()
