from __future__ import annotations

import getpass
import subprocess
import sys
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
APP_DIR = ROOT_DIR / "app"
ENV_FILE = APP_DIR / ".env.supabase.local"
SERVICE_ID = "srv-d8tujlho3t8c73c3h60g"
BUCKET = "job-assistant-users"


def prompt_required(label: str, *, secret: bool = False) -> str:
    while True:
        value = (getpass.getpass(label) if secret else input(label)).strip()
        if value:
            return value
        print("This value is required.")


def run(command: list[str], *, cwd: Path | None = None, timeout: int = 120) -> None:
    result = subprocess.run(command, cwd=str(cwd) if cwd else None, text=True, timeout=timeout)
    if result.returncode != 0:
        raise SystemExit(result.returncode)


def current_commit() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT_DIR,
        text=True,
        capture_output=True,
        timeout=20,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def main() -> None:
    subprocess.run(["open", "https://supabase.com/dashboard/projects"], check=False)
    print("Use a free Supabase project, then open Project Settings > API Keys.")
    print("You can paste either the new publishable/secret keys or the legacy anon/service_role keys.")
    print("")
    url = prompt_required("Project URL, like https://xxxx.supabase.co: ")
    public_key = prompt_required("Publishable or anon key: ", secret=True)
    admin_key = prompt_required("Secret or service_role key: ", secret=True)
    bucket = input(f"Storage bucket [{BUCKET}]: ").strip() or BUCKET

    ENV_FILE.write_text(
        "\n".join(
            [
                "# Generated by scripts/manual_free_cloud_setup.py",
                f"SUPABASE_URL={url}",
                f"SUPABASE_ANON_KEY={public_key}",
                f"SUPABASE_SERVICE_ROLE_KEY={admin_key}",
                "SUPABASE_JWT_SECRET=",
                f"SUPABASE_STORAGE_BUCKET={bucket}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    ENV_FILE.chmod(0o600)
    print(f"Wrote {ENV_FILE}")

    run([sys.executable, str(APP_DIR / "scripts" / "configure_render_supabase.py"), str(ENV_FILE)], timeout=120)
    deploy_command = ["render", "deploys", "create", SERVICE_ID, "--wait", "--confirm"]
    commit = current_commit()
    if commit:
        deploy_command[4:4] = ["--commit", commit]
    run(deploy_command, cwd=ROOT_DIR, timeout=600)
    run([sys.executable, str(APP_DIR / "scripts" / "check_render_status.py")], timeout=60)
    print("Free cloud save setup finished.")


if __name__ == "__main__":
    main()
